### ISSUE TITLE
Bug: Visibilidade do botao para retroceder no formulario de registo

### ISSUE THREAD

**Issue by BrunoGameiro** [antoniojps/voluntarios#14]

**Comment by antoniojps** [comment]
Também notei que o icon do botão "Voluntariar" da página inicial está invisivel. Vamos investigar @vascosilvaa.

**Comment by antoniojps** [comment]
Mhmm pelos vistos os Icons já não estão a adoptar o `font-size`, foi necessário declarar os tamanhos no css.

```css
    svg {
      height: 14px;
      width: 14px;
    }
```
